# Build the package and publish it to PyPI after tests pass.
# From https://discourse.jupyter.org/t/use-github-workflows-to-automatically-publish-to-pypi-when-new-tags-are-created/14941
# fetch-depth: 0 is needed to make `git describe` work.
name: Publish to PyPI
on:
  push


jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Stamp Git tag and version
        run: |
          V=$(git describe --tags | tr -d 'v' | tr '-' '.' | cut -d'.' -f 1-4)
          sed -i "s/_GIT_VERSION_/$V/" pyproject.toml
          cat pyproject.toml
      - name: Build package
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_KEY }}
          repository_url: https://test.pypi.org/legacy/
